memory_limit = 2056M
max_execution_time = 1800
max_input_time = 1800
post_max_size = 32M
upload_max_filesize = 32M

opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.validate_timestamps=1
opcache.revalidate_freq=2
