[www]

user = www-data
group = www-data

listen = 0.0.0.0:9000

pm.max_requests = 1000
pm.process_idle_timeout = 10s

pm = dynamic
pm.max_children = 80
pm.start_servers = 15
pm.min_spare_servers = 10
pm.max_spare_servers = 25

request_terminate_timeout = 120s
request_slowlog_timeout = 3s
slowlog = /proc/self/fd/2
